typography_spectrum: 0.88716
color:
  brandColors:
    - '#fafffe'
    - '#89847e'
    - '#0d140d'
    - '#9ec3f0'
    - '#4f4d3e'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-69607934-1
  facebook: null
  twitter: null
name: TomAnderson
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Tom Anderson
description: Excellency
purpose: []
content: []
github: true
author:
  name: Tom Anderson
