name: TomAnderson
favicon: null
layout_spectrum: 0.5387808971572667
typography_spectrum: 0.7944512311369181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.75
  lightness: 0.5291527130175382
  saturation: 0.31331325275823474
  rhythmicContrast: 0.1512398747727275
purpose: []
