name: TomAnderson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafffe'
    - '#89847e'
    - '#0d140d'
    - '#9ec3f0'
    - '#4f4d3e'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
